### ISSUE TITLE
Alignment fix of terms and condition page navbar

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1091]
### Description

i have been seen that in your terms and condition page navbar is not aligned properly i want to fix this

### Steps to Reproduce

1. resize it 
2. adjust gap
3. adjust margin

### Expected Behavior

i want to make this navbar as every page navbar look

### Actual Behavior

the all components of navbar shifting left

### Screenshots

![WhatsApp Image 2024-10-29 at 03 01 57_951202f2](https://github.com/user-attachments/assets/48b29813-deb9-4462-a70d-b1d2ab4d2f88)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by biswajit-sarkar-007** [comment]
i have also noticed that the alignment of navbar many of page is not proper i want to fix all pages navbar and make it like this
![WhatsApp Image 2024-10-29 at 03 06 00_c3cb67f9](https://github.com/user-attachments/assets/81d58293-6a42-4911-9f58-55f79da982a6)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

And one more thing this project and I am inactive due to some of my works.

Please do contribute to other projects.

I hope you understand.
