### ISSUE TITLE
[Mention The Feature]: Improve the UI of the navbar 

### ISSUE THREAD

**Issue by Aryan-01-star** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1102]
### Is your feature request related to a problem? Please describe.

Yes, my feature relates to a problem
An improvement in the overall UI of the website can result in better User interaction and improved User Experience for the website which will make it more likable and engaging for the user as the first impression of any website comes from its UI

### Describe the solution you'd like.

I would like to change the UI of the navbar section of the website also I would like to improve the UI of the website wherever needed in the entire website  

### Describe alternatives you've considered.

I have thought of changing the background color of the nav links in the navbar and also changing the color combination of the navbar itself for a more professional and advanced look of the website 

### Additional context.

In addition, I would like to inform you with what's the importance of this edit is that every website in today's era try to have the best of there UI design possible so if we promote change in the UI of the website it will result in a better UX causing a rapid growth in the demand of our website

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/5188728a-fe5a-43da-8383-92e532da2813)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

And one more thing this project and I am inactive for now due to some of my works.

Please do contribute to other projects I hope you understand.
