### ISSUE TITLE
the colour of the header section of the homepage is problematic.

### ISSUE THREAD

**Issue by aryy8** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1103]
its colour is greyish-black in light mode and black in dark mode so there is a negligible difference when we change the theme. this way user will think the website is already in dark mode so it should be change.

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar and header based issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar and header updates for now, as it was done and changes many times before. And for home pages also.

please understand.

And one more thing this project is going to be inactive from today evening including me. Due to some of my works, please do contribute to other projects.
