### ISSUE TITLE
Issue: Lack of 'Home' Navigation Item on Key Pages

### ISSUE THREAD

**Issue by umar-farooq-shaik** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1109]

**Comment by vivekvardhan2810** [comment]
see in some pages, there isn't any requirement for home button, as when user clicks the ml fusion lab logo, then it automatically redirects to home page.

so we don't require this.

so i am closing this issue.

please understand.

And one more thing this project and me are inactive for sometime due to some of my works.

please do work on other projects.

i hope you understand.
