### ISSUE TITLE
To make the navigation bar look presentable

### ISSUE THREAD

**Issue by piyahub** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1126]
### Description

the buttons come in 2 lines which does not look good.
I opened it on chrome, brave and Microsoft edge.

### Steps to Reproduce

 By managing the spacing and their size it could come to a single line and look good.
please assign it to me I will make it look better.

### Expected Behavior

It should come in a single line

### Actual Behavior

coming in 2 lines

### Screenshots

![image](https://github.com/user-attachments/assets/a0673efb-e835-42b8-92c2-22991268631a)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

And one more thing this project and I am inactive for now due to some of my works.

Please do contribute to other projects I hope you understand.
