### ISSUE TITLE
Navbar is not consistent across the website

### ISSUE THREAD

**Issue by shivam8112005** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1127]
### Description

The navbar appears inconsistent across different pages of the website. For instance, the styling and layout of the navbar vary between the homepage and the blog section. I tried applying the same CSS classes and HTML structure for the navbar on all pages, but the inconsistency persists.

### Steps to Reproduce

1. Open the website homepage.
2. Observe the navbar layout and styling.
3. Navigate to the blog section.
4. Compare the navbar with that of the homepage.
5. Note the differences in alignment, font size, and background color.

### Expected Behavior

I expected the navbar to maintain a consistent design, including the same styles, alignment, and functionality across all pages of the website.

### Actual Behavior

The navbar has different styles and layouts on various pages:

The font size is smaller on the blog section.
The background color changes inconsistently between pages.

### Screenshots

![Screenshot 2024-11-01 191744](https://github.com/user-attachments/assets/17b02b42-52f1-41dd-b33b-7298708de813)

### Additional Information

This inconsistency may be due to missing or differing CSS files or rules being applied on specific pages. A review of the CSS classes and HTML structure used for the navbar across all pages is recommended to ensure uniformity.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

And one more thing this project and I am inactive for now due to some of my works.

Please do contribute to other projects.

 I hope you understand.

**Comment by shivam8112005** [comment]
Ohk got it👍🏻
