### ISSUE TITLE
[Mention The Feature]: Parkinsons disease prediction 

### ISSUE THREAD

**Issue by kaishwarya24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1128]
### Is your feature request related to a problem? Please describe.

Parkinsons disease prediction using the Machine learning models 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

i think this is the wrong issue that you have kept, this is for website improvements. not for tutorials

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
