### ISSUE TITLE
Fix broken footer links in email.html page

### ISSUE THREAD

**Issue by GauraviSingh7** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1130]
### Description

The footer links on the `/pages/email.html` page are broken, resulting in navigation errors. The affected links include:
  - Contact Us
  - Privacy Policy
  - Terms and Conditions
  - Security
  - Contributors
  - About Us

### Steps to Reproduce

1. Go to the **Email Us** page via the footer link.
 2. Click on any of the following links: **Contact Us**, **Privacy Policy**, **Terms and Conditions**, **Security**, **Contributors**,**About Us**.

### Expected Behavior

Each link should navigate to its respective page.

### Actual Behavior

  Clicking these links currently results in a "Page Not Found" error.  
  Screenshot attached for reference

### Screenshots

![Screenshot (25)](https://github.com/user-attachments/assets/a072bebd-d932-4f1f-bb1c-932bf1dbf03d)

### Additional Information

I am a contributor to GSSoC'24 extd

### What browser are you seeing the problem on?

- [ ] Firefox
- [x] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, Thank you for raising this issue.

But for now it is not required as it is only updation links for email page only, we want only the main website page footer to be updated and it is there, so there is no need for other page footer updates.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.

**Comment by GauraviSingh7** [comment]
No worries, thank you!
