### ISSUE TITLE
[Mention The Feature]:  Want to redesign Testimonial page with mode ui features

### ISSUE THREAD

**Issue by mdfaizaanalam** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1137]
### Is your feature request related to a problem? Please describe.

As you can see below video demo testimonial page design is very simple so i want to enhancce its features and make it more attractive.

### Describe the solution you'd like.

I would like to redesign complete testimonial page with modern ui features.

### Show us the magic with screenshots

https://github.com/user-attachments/assets/ae2da397-432d-46ae-9d71-bd303315630d

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [ ] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, Thank you for raising the issue.

But for now it is not required and don't want any improvements on this page.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.

**Comment by vivekvardhan2810** [comment]
And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
