### ISSUE TITLE
Style.css update

### ISSUE THREAD

**Issue by Hemraj-7** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1138]
### Description

Hey ML-Fusion-Lab, sytle.css has complex it has a lot of times media query ( for device size < 768 ) and has unusual code. so i want to Update style.css file and make easy readable and easy understandable.

I will create only 2-3 media query ( for 3 type of devices ) according to the sizes and add all the media query in the these media query. I will remove unusual code and Extra media Queries.

Assign me this issue
Thank you.

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, Thank you for raising the issue.

But for now it is not required and don't want any improvements on this page.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.

**Comment by vivekvardhan2810** [comment]
And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
