### ISSUE TITLE
Added a cursor trail effect to TESTIMONIAL page

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1140]
### Is your feature request related to a problem? Please describe.

Added a cursor trail effect to TESTIMONIAL page, creating a subtle, interactive visual trail that follows the user's cursor as they navigate the page.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, Thank you for raising the issue.

But for now it is not required and don't want any improvements on this page.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.

**Comment by vivekvardhan2810** [comment]
And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand

**Comment by neeru24** [comment]
> And one more thing this project is already inactive including me also due to some of my works.
> 
> Please do contribute to other projects.
> 
> I hope you understand

Oh okay, No issues. It was not known to me that the project is inactive.
