### ISSUE TITLE
Bug: Incomplete Text Rendering in 'Learn More' Popup for Featured Projects.

### ISSUE THREAD

**Issue by synthiaekka** [ML-Fusion-Lab/ML-Fusion-Lab-Website#194]
![issue1](https://github.com/user-attachments/assets/77941bc6-225c-484b-90a1-44f49e9c3742)
I will implement the necessary changes to resolve the issue...could you assign me for this issue.

**Comment by vivekvardhan2810** [comment]
@synthiaekka assigned this issue to you.

Make sure to join discord server and complete this issue in the next 2 days.

**Comment by pameladeysarkar2003** [comment]
@vivekvardhan2810 please assign me with this task i will make necessary changes to solve the issues.
I've also noticed if I toggle the font-family CSS attribute in the console on and off it remedies the appearance... Additionally if I refresh the page (instead of using the on-site navigation) it also seems to render properly. I've not been able to replicate this on another machine with the latest version of Chrome, but it is consistent across my development and test environments. The only extensions I am using are Disconnect, AdBlock, PageSpeed Insights, an RSS reader, and Javascript Quickswithcer... All other browsers appear to behave as expected.

**Comment by synthiaekka** [comment]
> @synthiaekka assigned this issue to you.
> 
> Make sure to join discord server and complete this issue in the next 2 days.
Okay!
