### ISSUE TITLE
I want to re design this About Us whole page

### ISSUE THREAD

**Issue by Suvadip-sana** [ML-Fusion-Lab/ML-Fusion-Lab-Website#51]
Hi! My self Suvadip Sana
**ISSUE**
This About Us page is not good looking, visually not appealing.
I want to design this whole page according to the color pallet of the website.

Please assign me that issue. I want to work on it.
I am also a hacktober fest participant. Please add this lebel

**Comment by vivekvardhan2810** [comment]
Hi, @Suvadip-sana , this issue was mentioned before and kept for Pull request. and it is ready to merge.

I would encourage you to look for other issues at website improvements, then you can create new issue. i will be very happy for you to contribute on this repository more.

for now i am closing this issue.

make sure to join discord channel: https://discord.gg/FZxBRpTEeH, for further updates and communications.
