### ISSUE TITLE
Improving the whole Design and style of the home page and updating the Navbar

### ISSUE THREAD

**Issue by hritika2409** [ML-Fusion-Lab/ML-Fusion-Lab-Website#52]
<img width="938" alt="image" src="https://github.com/user-attachments/assets/066bfe4a-a799-47c8-b830-fdfc0b64a4f4">

**Comment by vivekvardhan2810** [comment]
Hi, @hritika2409, This issue was mentioned before and completed.

i would encourage you to look for other issues in website for improvement and suggestions, Then you can create new issue.

For now i am closing this issue.

make sure to join our discord channel: https://discord.gg/FZxBRpTEeH, for further updates and communications.
