### ISSUE TITLE
[Mention The Feature]: UI of the navbar

### ISSUE THREAD

**Issue by shriyadindi** [ML-Fusion-Lab/ML-Fusion-Lab-Website#581]
### Is your feature request related to a problem? Please describe.

I would like to change the UI of the navbar and modify it for better navigation

### Show us the magic with screenshots

![Screenshot (390)](https://github.com/user-attachments/assets/7884b445-2d42-47dc-8e62-3aeb7fb49859)
![Screenshot (389)](https://github.com/user-attachments/assets/cb57f237-0280-4442-a981-2bc23da83ae1)

_No response_

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@shriyadindi this issue was assigned before, you can check this in issues section and they are updating it.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.

**Comment by shriyadindi** [comment]
@vivekvardhan2810 kindly go though my request and assign me the task

**Comment by vivekvardhan2810** [comment]
@shriyadindi please check the issues section, the navbar updation was assigned before, please check it.
