### ISSUE TITLE
 Fix Navbar Positioning and Improve Text Visibility

### ISSUE THREAD

**Issue by Swyom** [ML-Fusion-Lab/ML-Fusion-Lab-Website#583]
### Issue Description

1.Navbar Items Alignment: The items in the navbar are not aligned properly, making the layout look inconsistent and unprofessional.
2.Navbar Positioning: The navbar is not fixed to the top of the page, causing it to scroll out of view when the user scrolls down the page.

### Additional Context

1.Review the design to ensure the navbar looks consistent across different devices.
2.Consider adding some additional styling to improve the user experience and interaction with the navbar.

### Screenshots or Examples (if applicable)

![Screenshot from 2024-10-14 13-05-42](https://github.com/user-attachments/assets/ffecee35-9b55-4ea3-b943-c5a2c5e251d1)

### Proposed Solution (optional)

1.Fix Navbar Position: Add the following CSS to ensure the navbar stays fixed at the top of the screen
2.Improve Navbar Item Alignment: Adjust the CSS to ensure proper spacing and alignment of the navbar items
3.Ensure Mobile Responsiveness: Ensure that the navbar items are responsive and collapse appropriately on smaller screens

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [ ] I am willing to work on this issue (optional)

**Comment by Swyom** [comment]
I really want to work on it ,assign me to fix this issue

**Comment by vivekvardhan2810** [comment]
@Swyom this issue was assigned before, you can check this in issues section and they are updating it.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
