### ISSUE TITLE
Navbar Section is not fully responsive

### ISSUE THREAD

**Issue by Gautamchandar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#633]
### Issue Description

Your navbar section is not responsive.
Assign this Task. I can solve that @ML-Fusion-Lab
I am contributor Under GSSOC^24

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/5d05400a-7c0b-4708-a990-2594e11ac318)

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
This issue was assigned before and he is working on it.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
